set_property direction IN [get_ports {iSFP_LOS[3]}]
set_property direction IN [get_ports {iSFP_LOS[2]}]
set_property direction IN [get_ports {iSFP_LOS[1]}]
set_property direction OUT [get_ports {oHIP_SERIAL_TX_OUT7}]
set_property direction OUT [get_ports {oHIP_SERIAL_TX_OUT5}]
set_property direction OUT [get_ports {oHIP_SERIAL_TX_OUT3}]
set_property direction OUT [get_ports {oHIP_SERIAL_TX_OUT1}]
set_property direction INOUT [get_ports {ioFPGA_DATA[3]}]
set_property direction INOUT [get_ports {ioFPGA_DATA[2]}]
set_property direction INOUT [get_ports {ioFPGA_DATA[1]}]
set_property direction IN [get_ports {sys_rst_n}]
set_property direction IN [get_ports {iFC_RD_N[18]}]
set_property direction IN [get_ports {iFC_RD_P[18]}]
set_property direction OUT [get_ports {oFC_TD_N[18]}]
set_property direction OUT [get_ports {oFC_TD_P[18]}]
set_property direction IN [get_ports {iFC_RD_N[17]}]
set_property direction IN [get_ports {iFC_RD_P[17]}]
set_property direction OUT [get_ports {oFC_TD_N[17]}]
set_property direction OUT [get_ports {oFC_TD_P[17]}]
set_property direction IN [get_ports {iFC_RD_N[16]}]
set_property direction IN [get_ports {iFC_RD_P[16]}]
set_property direction OUT [get_ports {oFC_TD_N[16]}]
set_property direction OUT [get_ports {oFC_TD_P[16]}]
set_property direction IN [get_ports {iFC_RD_N[15]}]
set_property direction IN [get_ports {iFC_RD_P[15]}]
set_property direction OUT [get_ports {oFC_TD_N[15]}]
set_property direction OUT [get_ports {oFC_TD_P[15]}]
set_property direction IN [get_ports {iFC_RD_N[14]}]
set_property direction IN [get_ports {iFC_RD_P[14]}]
set_property direction OUT [get_ports {oFC_TD_N[14]}]
set_property direction OUT [get_ports {oFC_TD_P[14]}]
set_property direction IN [get_ports {iFC_RD_N[13]}]
set_property direction IN [get_ports {iFC_RD_P[13]}]
set_property direction OUT [get_ports {oFC_TD_N[13]}]
set_property direction OUT [get_ports {oFC_TD_P[13]}]
set_property direction IN [get_ports {iFC_RD_N[12]}]
set_property direction IN [get_ports {iFC_RD_P[12]}]
set_property direction OUT [get_ports {oFC_TD_N[12]}]
set_property direction OUT [get_ports {oFC_TD_P[12]}]
set_property direction IN [get_ports {iFC_RD_N[11]}]
set_property direction IN [get_ports {iFC_RD_P[11]}]
set_property direction OUT [get_ports {oFC_TD_N[11]}]
set_property direction OUT [get_ports {oFC_TD_P[11]}]
set_property direction IN [get_ports {iFC_RD_N[10]}]
set_property direction IN [get_ports {iFC_RD_P[10]}]
set_property direction OUT [get_ports {oFC_TD_N[10]}]
set_property direction OUT [get_ports {oFC_TD_P[10]}]
set_property direction IN [get_ports {iCLK_FC_425_N[1]}]
set_property direction IN [get_ports {iCLK_FC_425_P[1]}]
set_property direction IN [get_ports {iFC_RD_N[9]}]
set_property direction IN [get_ports {iFC_RD_P[9]}]
set_property direction OUT [get_ports {oFC_TD_N[9]}]
set_property direction OUT [get_ports {oFC_TD_P[9]}]
set_property direction IN [get_ports {iFC_RD_N[8]}]
set_property direction IN [get_ports {iFC_RD_P[8]}]
set_property direction OUT [get_ports {oFC_TD_N[8]}]
set_property direction OUT [get_ports {oFC_TD_P[8]}]
set_property direction IN [get_ports {iFC_RD_N[7]}]
set_property direction IN [get_ports {iFC_RD_P[7]}]
set_property direction OUT [get_ports {oFC_TD_N[7]}]
set_property direction OUT [get_ports {oFC_TD_P[7]}]
set_property direction IN [get_ports {iFC_RD_N[6]}]
set_property direction IN [get_ports {iFC_RD_P[6]}]
set_property direction OUT [get_ports {oFC_TD_N[6]}]
set_property direction OUT [get_ports {oFC_TD_P[6]}]
set_property direction IN [get_ports {iFC_RD_N[5]}]
set_property direction IN [get_ports {iFC_RD_P[5]}]
set_property direction OUT [get_ports {oFC_TD_N[5]}]
set_property direction OUT [get_ports {oFC_TD_P[5]}]
set_property direction IN [get_ports {iFC_RD_N[4]}]
set_property direction IN [get_ports {iFC_RD_P[4]}]
set_property direction OUT [get_ports {oFC_TD_N[4]}]
set_property direction OUT [get_ports {oFC_TD_P[4]}]
set_property direction IN [get_ports {iFC_RD_N[3]}]
set_property direction IN [get_ports {iFC_RD_P[3]}]
set_property direction OUT [get_ports {oFC_TD_N[3]}]
set_property direction OUT [get_ports {oFC_TD_P[3]}]
set_property direction IN [get_ports {iFC_RD_N[2]}]
set_property direction IN [get_ports {iFC_RD_P[2]}]
set_property direction OUT [get_ports {oFC_TD_N[2]}]
set_property direction OUT [get_ports {oFC_TD_P[2]}]
set_property direction IN [get_ports {iFC_RD_N[1]}]
set_property direction IN [get_ports {iFC_RD_P[1]}]
set_property direction OUT [get_ports {oFC_TD_N[1]}]
set_property direction OUT [get_ports {oFC_TD_P[1]}]
set_property direction IN [get_ports {iFC_RD_N[0]}]
set_property direction IN [get_ports {iFC_RD_P[0]}]
set_property direction OUT [get_ports {oFC_TD_N[0]}]
set_property direction OUT [get_ports {oFC_TD_P[0]}]
set_property direction IN [get_ports {iSFP_LOS[7]}]
set_property direction IN [get_ports {iSFP_LOS[5]}]
set_property direction IN [get_ports {iSFP_LOS[4]}]
set_property direction IN [get_ports {iSFP_LOS[0]}]
set_property direction OUT [get_ports {oHIP_SERIAL_TX_OUT6}]
set_property direction OUT [get_ports {oHIP_SERIAL_TX_OUT4}]
set_property direction OUT [get_ports {oHIP_SERIAL_TX_OUT2}]
set_property direction OUT [get_ports {oHIP_SERIAL_TX_OUT0}]
set_property direction INOUT [get_ports {ioFPGA_DATA[5]}]
set_property direction INOUT [get_ports {ioFPGA_DATA[0]}]
set_property direction IN [get_ports {iSFP_LOS[6]}]
set_property direction IN [get_ports {iSFP_LOS[11]}]
set_property direction IN [get_ports {iSFP_LOS[9]}]
set_property direction IN [get_ports {iSFP_LOS[8]}]
set_property direction OUT [get_ports {oTXD}]
set_property direction INOUT [get_ports {ioFPGA_DATA[7]}]
set_property direction INOUT [get_ports {ioFPGA_DATA[4]}]
set_property direction IN [get_ports {iSFP_LOS[13]}]
set_property direction IN [get_ports {iSFP_LOS[12]}]
set_property direction IN [get_ports {iSFP_LOS[10]}]
set_property direction IN [get_ports {iSFP_LOS[15]}]
set_property direction IN [get_ports {iSFP_LOS[14]}]
set_property direction INOUT [get_ports {ioFPGA_DATA[6]}]
set_property direction OUT [get_ports {oLED_N[1]}]
set_property direction IN [get_ports {iSFP_LOS[17]}]
set_property direction IN [get_ports {iSFP_LOS[21]}]
set_property direction IN [get_ports {iSFP_LOS[23]}]
set_property direction IN [get_ports {iSFP_LOS[22]}]
set_property direction OUT [get_ports {oLED_N[5]}]
set_property direction OUT [get_ports {oLED_N[0]}]
set_property direction IN [get_ports {iSFP_LOS[16]}]
set_property direction IN [get_ports {iSFP_LOS[19]}]
set_property direction IN [get_ports {iSFP_LOS[18]}]
set_property direction IN [get_ports {iSFP_LOS[20]}]
set_property direction OUT [get_ports {oLED_N[4]}]
set_property direction OUT [get_ports {oLED_N[3]}]
set_property direction OUT [get_ports {oLED_N[2]}]
set_property direction OUT [get_ports {oLED_N[9]}]
set_property direction OUT [get_ports {oLED_N[7]}]
set_property direction OUT [get_ports {oLED_N[6]}]
set_property direction IN [get_ports {iCLK_425M_P[0]}]
set_property direction OUT [get_ports {oLED_N[8]}]
set_property direction OUT [get_ports {oLED_N[11]}]
set_property direction OUT [get_ports {oLED_N[10]}]
set_property direction OUT [get_ports {oLED_N[13]}]
set_property direction OUT [get_ports {oLED_N[12]}]
set_property direction OUT [get_ports {oLED_N[15]}]
set_property direction OUT [get_ports {oLED_N[14]}]
set_property direction IN [get_ports {iBUS_EN}]
set_property direction IN [get_ports {iBUS_CLK}]
set_property direction INOUT [get_ports {ioSYNC_NEIGHBOR}]
set_property direction IN [get_ports {iBUS_RST}]
set_property direction IN [get_ports {iBUS_MASTER}]
set_property direction IN [get_ports {iFPGA_RSTN}]
set_property direction OUT [get_ports {oFC_RATE_SEL[3]}]
set_property direction OUT [get_ports {pci_exp_txp[0]}]
set_property direction OUT [get_ports {pci_exp_txn[0]}]
set_property direction OUT [get_ports {oFC_RATE_SEL[0]}]
set_property direction OUT [get_ports {oFC_RATE_SEL[1]}]
set_property direction IN [get_ports {iCLK_FR}]
set_property direction OUT [get_ports {oFC_RATE_SEL[2]}]
set_property direction OUT [get_ports {pci_exp_txp[1]}]
set_property direction OUT [get_ports {pci_exp_txn[1]}]
set_property direction INOUT [get_ports {ioSYNC_RIBBON}]
set_property direction OUT [get_ports {oFC_RATE_SEL[5]}]
set_property direction OUT [get_ports {oFC_RATE_SEL[4]}]
set_property direction OUT [get_ports {oFC_RATE_SEL[7]}]
set_property direction OUT [get_ports {oFC_RATE_SEL[6]}]
set_property direction OUT [get_ports {pci_exp_txp[2]}]
set_property direction OUT [get_ports {pci_exp_txn[2]}]
set_property direction IN [get_ports {pci_exp_rxp[0]}]
set_property direction IN [get_ports {pci_exp_rxn[0]}]
set_property direction IN [get_ports {iFC_RD_N[25]}]
set_property direction IN [get_ports {iFC_RD_P[25]}]
set_property direction OUT [get_ports {oFC_TD_N[25]}]
set_property direction OUT [get_ports {oFC_TD_P[25]}]
set_property direction OUT [get_ports {oFC_RATE_SEL[9]}]
set_property direction OUT [get_ports {oFC_RATE_SEL[8]}]
set_property direction OUT [get_ports {oFC_RATE_SEL[11]}]
set_property direction OUT [get_ports {oFC_RATE_SEL[10]}]
set_property direction OUT [get_ports {pci_exp_txp[3]}]
set_property direction OUT [get_ports {pci_exp_txn[3]}]
set_property direction IN [get_ports {pci_exp_rxp[1]}]
set_property direction IN [get_ports {pci_exp_rxn[1]}]
set_property direction IN [get_ports {iFC_RD_N[24]}]
set_property direction IN [get_ports {iFC_RD_P[24]}]
set_property direction OUT [get_ports {oFC_TD_N[24]}]
set_property direction OUT [get_ports {oFC_TD_P[24]}]
set_property direction OUT [get_ports {pci_exp_txp[4]}]
set_property direction OUT [get_ports {pci_exp_txn[4]}]
set_property direction IN [get_ports {pci_exp_rxp[2]}]
set_property direction IN [get_ports {pci_exp_rxn[2]}]
set_property direction IN [get_ports {iFC_RD_N[23]}]
set_property direction IN [get_ports {iFC_RD_P[23]}]
set_property direction OUT [get_ports {oFC_TD_N[23]}]
set_property direction OUT [get_ports {oFC_TD_P[23]}]
set_property direction IN [get_ports {sys_clk_p}]
set_property direction IN [get_ports {sys_clk_n}]
set_property direction OUT [get_ports {pci_exp_txp[5]}]
set_property direction OUT [get_ports {pci_exp_txn[5]}]
set_property direction IN [get_ports {pci_exp_rxp[3]}]
set_property direction IN [get_ports {pci_exp_rxn[3]}]
set_property direction IN [get_ports {iFC_RD_N[22]}]
set_property direction IN [get_ports {iFC_RD_P[22]}]
set_property direction OUT [get_ports {oFC_TD_N[22]}]
set_property direction OUT [get_ports {oFC_TD_P[22]}]
set_property direction OUT [get_ports {pci_exp_txp[6]}]
set_property direction OUT [get_ports {pci_exp_txn[6]}]
set_property direction IN [get_ports {pci_exp_rxp[4]}]
set_property direction IN [get_ports {pci_exp_rxn[4]}]
set_property direction IN [get_ports {iFC_RD_N[21]}]
set_property direction IN [get_ports {iFC_RD_P[21]}]
set_property direction OUT [get_ports {oFC_TD_N[21]}]
set_property direction OUT [get_ports {oFC_TD_P[21]}]
set_property direction OUT [get_ports {pci_exp_txp[7]}]
set_property direction OUT [get_ports {pci_exp_txn[7]}]
set_property direction IN [get_ports {pci_exp_rxp[5]}]
set_property direction IN [get_ports {pci_exp_rxn[5]}]
set_property direction IN [get_ports {iFC_RD_N[20]}]
set_property direction IN [get_ports {iFC_RD_P[20]}]
set_property direction OUT [get_ports {oFC_TD_N[20]}]
set_property direction OUT [get_ports {oFC_TD_P[20]}]
set_property direction IN [get_ports {iCLK_FC_425_N[0]}]
set_property direction IN [get_ports {iCLK_FC_425_P[0]}]
set_property direction IN [get_ports {pci_exp_rxp[6]}]
set_property direction IN [get_ports {pci_exp_rxn[6]}]
set_property direction IN [get_ports {iFC_RD_N[19]}]
set_property direction IN [get_ports {iFC_RD_P[19]}]
set_property direction OUT [get_ports {oFC_TD_N[19]}]
set_property direction OUT [get_ports {oFC_TD_P[19]}]
set_property direction IN [get_ports {pci_exp_rxp[7]}]
set_property direction IN [get_ports {pci_exp_rxn[7]}]
make_diff_pair_ports iFC_RD_P[18] iFC_RD_N[18]
make_diff_pair_ports oFC_TD_P[18] oFC_TD_N[18]
make_diff_pair_ports iFC_RD_P[17] iFC_RD_N[17]
make_diff_pair_ports oFC_TD_P[17] oFC_TD_N[17]
make_diff_pair_ports iFC_RD_P[16] iFC_RD_N[16]
make_diff_pair_ports oFC_TD_P[16] oFC_TD_N[16]
make_diff_pair_ports iFC_RD_P[15] iFC_RD_N[15]
make_diff_pair_ports oFC_TD_P[15] oFC_TD_N[15]
make_diff_pair_ports iFC_RD_P[14] iFC_RD_N[14]
make_diff_pair_ports oFC_TD_P[14] oFC_TD_N[14]
make_diff_pair_ports iFC_RD_P[13] iFC_RD_N[13]
make_diff_pair_ports oFC_TD_P[13] oFC_TD_N[13]
make_diff_pair_ports iFC_RD_P[12] iFC_RD_N[12]
make_diff_pair_ports oFC_TD_P[12] oFC_TD_N[12]
make_diff_pair_ports iFC_RD_P[11] iFC_RD_N[11]
make_diff_pair_ports oFC_TD_P[11] oFC_TD_N[11]
make_diff_pair_ports iFC_RD_P[10] iFC_RD_N[10]
make_diff_pair_ports oFC_TD_P[10] oFC_TD_N[10]
make_diff_pair_ports iCLK_FC_425_P[1] iCLK_FC_425_N[1]
make_diff_pair_ports iFC_RD_P[9] iFC_RD_N[9]
make_diff_pair_ports oFC_TD_P[9] oFC_TD_N[9]
make_diff_pair_ports iFC_RD_P[8] iFC_RD_N[8]
make_diff_pair_ports oFC_TD_P[8] oFC_TD_N[8]
make_diff_pair_ports iFC_RD_P[7] iFC_RD_N[7]
make_diff_pair_ports oFC_TD_P[7] oFC_TD_N[7]
make_diff_pair_ports iFC_RD_P[6] iFC_RD_N[6]
make_diff_pair_ports oFC_TD_P[6] oFC_TD_N[6]
make_diff_pair_ports iFC_RD_P[5] iFC_RD_N[5]
make_diff_pair_ports oFC_TD_P[5] oFC_TD_N[5]
make_diff_pair_ports iFC_RD_P[4] iFC_RD_N[4]
make_diff_pair_ports oFC_TD_P[4] oFC_TD_N[4]
make_diff_pair_ports iFC_RD_P[3] iFC_RD_N[3]
make_diff_pair_ports oFC_TD_P[3] oFC_TD_N[3]
make_diff_pair_ports iFC_RD_P[2] iFC_RD_N[2]
make_diff_pair_ports oFC_TD_P[2] oFC_TD_N[2]
make_diff_pair_ports iFC_RD_P[1] iFC_RD_N[1]
make_diff_pair_ports oFC_TD_P[1] oFC_TD_N[1]
make_diff_pair_ports iFC_RD_P[0] iFC_RD_N[0]
make_diff_pair_ports oFC_TD_P[0] oFC_TD_N[0]
make_diff_pair_ports iFC_RD_P[25] iFC_RD_N[25]
make_diff_pair_ports oFC_TD_P[25] oFC_TD_N[25]
make_diff_pair_ports iFC_RD_P[24] iFC_RD_N[24]
make_diff_pair_ports oFC_TD_P[24] oFC_TD_N[24]
make_diff_pair_ports iFC_RD_P[23] iFC_RD_N[23]
make_diff_pair_ports oFC_TD_P[23] oFC_TD_N[23]
make_diff_pair_ports iFC_RD_P[22] iFC_RD_N[22]
make_diff_pair_ports oFC_TD_P[22] oFC_TD_N[22]
make_diff_pair_ports iFC_RD_P[21] iFC_RD_N[21]
make_diff_pair_ports oFC_TD_P[21] oFC_TD_N[21]
make_diff_pair_ports iFC_RD_P[20] iFC_RD_N[20]
make_diff_pair_ports oFC_TD_P[20] oFC_TD_N[20]
make_diff_pair_ports iCLK_FC_425_P[0] iCLK_FC_425_N[0]
make_diff_pair_ports iFC_RD_P[19] iFC_RD_N[19]
make_diff_pair_ports oFC_TD_P[19] oFC_TD_N[19]
set_property PACKAGE_PIN A3 [get_ports {iSFP_LOS[3]}]
set_property PACKAGE_PIN A4 [get_ports {iSFP_LOS[2]}]
set_property PACKAGE_PIN A6 [get_ports {iSFP_LOS[1]}]
set_property PACKAGE_PIN A7 [get_ports oHIP_SERIAL_TX_OUT7]
set_property PACKAGE_PIN A8 [get_ports oHIP_SERIAL_TX_OUT5]
set_property PACKAGE_PIN A9 [get_ports oHIP_SERIAL_TX_OUT3]
set_property PACKAGE_PIN A11 [get_ports oHIP_SERIAL_TX_OUT1]
set_property PACKAGE_PIN A12 [get_ports {ioFPGA_DATA[3]}]
set_property PACKAGE_PIN A13 [get_ports {ioFPGA_DATA[2]}]
set_property PACKAGE_PIN A14 [get_ports {ioFPGA_DATA[1]}]
set_property PACKAGE_PIN A28 [get_ports sys_rst_n]
set_property PACKAGE_PIN AA3 [get_ports {iFC_RD_N[18]}]
set_property PACKAGE_PIN AA4 [get_ports {iFC_RD_P[18]}]
set_property PACKAGE_PIN AA7 [get_ports {oFC_TD_N[18]}]
set_property PACKAGE_PIN AA8 [get_ports {oFC_TD_P[18]}]
set_property PACKAGE_PIN AB1 [get_ports {iFC_RD_N[17]}]
set_property PACKAGE_PIN AB2 [get_ports {iFC_RD_P[17]}]
set_property PACKAGE_PIN AB5 [get_ports {oFC_TD_N[17]}]
set_property PACKAGE_PIN AB6 [get_ports {oFC_TD_P[17]}]
set_property PACKAGE_PIN AC3 [get_ports {iFC_RD_N[16]}]
set_property PACKAGE_PIN AC4 [get_ports {iFC_RD_P[16]}]
set_property PACKAGE_PIN AC7 [get_ports {oFC_TD_N[16]}]
set_property PACKAGE_PIN AC8 [get_ports {oFC_TD_P[16]}]
set_property PACKAGE_PIN AD1 [get_ports {iFC_RD_N[15]}]
set_property PACKAGE_PIN AD2 [get_ports {iFC_RD_P[15]}]
set_property PACKAGE_PIN AD5 [get_ports {oFC_TD_N[15]}]
set_property PACKAGE_PIN AD6 [get_ports {oFC_TD_P[15]}]
set_property PACKAGE_PIN AE3 [get_ports {iFC_RD_N[14]}]
set_property PACKAGE_PIN AE4 [get_ports {iFC_RD_P[14]}]
set_property PACKAGE_PIN AE7 [get_ports {oFC_TD_N[14]}]
set_property PACKAGE_PIN AE8 [get_ports {oFC_TD_P[14]}]
set_property PACKAGE_PIN AF1 [get_ports {iFC_RD_N[13]}]
set_property PACKAGE_PIN AF2 [get_ports {iFC_RD_P[13]}]
set_property PACKAGE_PIN AF5 [get_ports {oFC_TD_N[13]}]
set_property PACKAGE_PIN AF6 [get_ports {oFC_TD_P[13]}]
set_property PACKAGE_PIN AG3 [get_ports {iFC_RD_N[12]}]
set_property PACKAGE_PIN AG4 [get_ports {iFC_RD_P[12]}]
set_property PACKAGE_PIN AG7 [get_ports {oFC_TD_N[12]}]
set_property PACKAGE_PIN AG8 [get_ports {oFC_TD_P[12]}]
set_property PACKAGE_PIN AH1 [get_ports {iFC_RD_N[11]}]
set_property PACKAGE_PIN AH2 [get_ports {iFC_RD_P[11]}]
set_property PACKAGE_PIN AH5 [get_ports {oFC_TD_N[11]}]
set_property PACKAGE_PIN AH6 [get_ports {oFC_TD_P[11]}]
set_property PACKAGE_PIN AJ3 [get_ports {iFC_RD_N[10]}]
set_property PACKAGE_PIN AJ4 [get_ports {iFC_RD_P[10]}]
set_property PACKAGE_PIN AJ7 [get_ports {oFC_TD_N[10]}]
set_property PACKAGE_PIN AJ8 [get_ports {oFC_TD_P[10]}]
set_property PACKAGE_PIN AJ11 [get_ports {iCLK_FC_425_N[1]}]
set_property PACKAGE_PIN AJ12 [get_ports {iCLK_FC_425_P[1]}]
set_property PACKAGE_PIN AK1 [get_ports {iFC_RD_N[9]}]
set_property PACKAGE_PIN AK2 [get_ports {iFC_RD_P[9]}]
set_property PACKAGE_PIN AK5 [get_ports {oFC_TD_N[9]}]
set_property PACKAGE_PIN AK6 [get_ports {oFC_TD_P[9]}]
set_property PACKAGE_PIN AL3 [get_ports {iFC_RD_N[8]}]
set_property PACKAGE_PIN AL4 [get_ports {iFC_RD_P[8]}]
set_property PACKAGE_PIN AL7 [get_ports {oFC_TD_N[8]}]
set_property PACKAGE_PIN AL8 [get_ports {oFC_TD_P[8]}]
set_property PACKAGE_PIN AM1 [get_ports {iFC_RD_N[7]}]
set_property PACKAGE_PIN AM2 [get_ports {iFC_RD_P[7]}]
set_property PACKAGE_PIN AM5 [get_ports {oFC_TD_N[7]}]
set_property PACKAGE_PIN AM6 [get_ports {oFC_TD_P[7]}]
set_property PACKAGE_PIN AN3 [get_ports {iFC_RD_N[6]}]
set_property PACKAGE_PIN AN4 [get_ports {iFC_RD_P[6]}]
set_property PACKAGE_PIN AN7 [get_ports {oFC_TD_N[6]}]
set_property PACKAGE_PIN AN8 [get_ports {oFC_TD_P[6]}]
set_property PACKAGE_PIN AP1 [get_ports {iFC_RD_N[5]}]
set_property PACKAGE_PIN AP2 [get_ports {iFC_RD_P[5]}]
set_property PACKAGE_PIN AP5 [get_ports {oFC_TD_N[5]}]
set_property PACKAGE_PIN AP6 [get_ports {oFC_TD_P[5]}]
set_property PACKAGE_PIN AR3 [get_ports {iFC_RD_N[4]}]
set_property PACKAGE_PIN AR4 [get_ports {iFC_RD_P[4]}]
set_property PACKAGE_PIN AR7 [get_ports {oFC_TD_N[4]}]
set_property PACKAGE_PIN AR8 [get_ports {oFC_TD_P[4]}]
set_property PACKAGE_PIN AT1 [get_ports {iFC_RD_N[3]}]
set_property PACKAGE_PIN AT2 [get_ports {iFC_RD_P[3]}]
set_property PACKAGE_PIN AT5 [get_ports {oFC_TD_N[3]}]
set_property PACKAGE_PIN AT6 [get_ports {oFC_TD_P[3]}]
set_property PACKAGE_PIN AU3 [get_ports {iFC_RD_N[2]}]
set_property PACKAGE_PIN AU4 [get_ports {iFC_RD_P[2]}]
set_property PACKAGE_PIN AU7 [get_ports {oFC_TD_N[2]}]
set_property PACKAGE_PIN AU8 [get_ports {oFC_TD_P[2]}]
set_property PACKAGE_PIN AV1 [get_ports {iFC_RD_N[1]}]
set_property PACKAGE_PIN AV2 [get_ports {iFC_RD_P[1]}]
set_property PACKAGE_PIN AV5 [get_ports {oFC_TD_N[1]}]
set_property PACKAGE_PIN AV6 [get_ports {oFC_TD_P[1]}]
set_property PACKAGE_PIN AW3 [get_ports {iFC_RD_N[0]}]
set_property PACKAGE_PIN AW4 [get_ports {iFC_RD_P[0]}]
set_property PACKAGE_PIN AW7 [get_ports {oFC_TD_N[0]}]
set_property PACKAGE_PIN AW8 [get_ports {oFC_TD_P[0]}]
set_property PACKAGE_PIN B2 [get_ports {iSFP_LOS[7]}]
set_property PACKAGE_PIN B4 [get_ports {iSFP_LOS[5]}]
set_property PACKAGE_PIN B5 [get_ports {iSFP_LOS[4]}]
set_property PACKAGE_PIN B6 [get_ports {iSFP_LOS[0]}]
set_property PACKAGE_PIN B7 [get_ports oHIP_SERIAL_TX_OUT6]
set_property PACKAGE_PIN B9 [get_ports oHIP_SERIAL_TX_OUT4]
set_property PACKAGE_PIN B10 [get_ports oHIP_SERIAL_TX_OUT2]
set_property PACKAGE_PIN B11 [get_ports oHIP_SERIAL_TX_OUT0]
set_property PACKAGE_PIN B12 [get_ports {ioFPGA_DATA[5]}]
set_property PACKAGE_PIN B14 [get_ports {ioFPGA_DATA[0]}]
set_property PACKAGE_PIN C2 [get_ports {iSFP_LOS[6]}]
set_property PACKAGE_PIN C3 [get_ports {iSFP_LOS[11]}]
set_property PACKAGE_PIN C4 [get_ports {iSFP_LOS[9]}]
set_property PACKAGE_PIN C5 [get_ports {iSFP_LOS[8]}]
set_property PACKAGE_PIN C10 [get_ports oTXD]
set_property PACKAGE_PIN C12 [get_ports {ioFPGA_DATA[7]}]
set_property PACKAGE_PIN C13 [get_ports {ioFPGA_DATA[4]}]
set_property PACKAGE_PIN D1 [get_ports {iSFP_LOS[13]}]
set_property PACKAGE_PIN D2 [get_ports {iSFP_LOS[12]}]
set_property PACKAGE_PIN D3 [get_ports {iSFP_LOS[10]}]
set_property PACKAGE_PIN D5 [get_ports {iSFP_LOS[15]}]
set_property PACKAGE_PIN D6 [get_ports {iSFP_LOS[14]}]
set_property PACKAGE_PIN D12 [get_ports {ioFPGA_DATA[6]}]
set_property PACKAGE_PIN D13 [get_ports {oLED_N[1]}]
set_property PACKAGE_PIN E1 [get_ports {iSFP_LOS[17]}]
set_property PACKAGE_PIN E3 [get_ports {iSFP_LOS[21]}]
set_property PACKAGE_PIN E4 [get_ports {iSFP_LOS[23]}]
set_property PACKAGE_PIN E5 [get_ports {iSFP_LOS[22]}]
set_property PACKAGE_PIN E11 [get_ports {oLED_N[5]}]
set_property PACKAGE_PIN E13 [get_ports {oLED_N[0]}]
set_property PACKAGE_PIN F1 [get_ports {iSFP_LOS[16]}]
set_property PACKAGE_PIN F2 [get_ports {iSFP_LOS[19]}]
set_property PACKAGE_PIN F3 [get_ports {iSFP_LOS[18]}]
set_property PACKAGE_PIN F4 [get_ports {iSFP_LOS[20]}]
set_property PACKAGE_PIN F11 [get_ports {oLED_N[4]}]
set_property PACKAGE_PIN F12 [get_ports {oLED_N[3]}]
set_property PACKAGE_PIN F13 [get_ports {oLED_N[2]}]
set_property PACKAGE_PIN G10 [get_ports {oLED_N[9]}]
set_property PACKAGE_PIN G11 [get_ports {oLED_N[7]}]
set_property PACKAGE_PIN G12 [get_ports {oLED_N[6]}]
set_property PACKAGE_PIN G17 [get_ports {iCLK_425M_P[0]}]
set_property PACKAGE_PIN H10 [get_ports {oLED_N[8]}]
set_property PACKAGE_PIN H12 [get_ports {oLED_N[11]}]
set_property PACKAGE_PIN H13 [get_ports {oLED_N[10]}]
set_property PACKAGE_PIN J10 [get_ports {oLED_N[13]}]
set_property PACKAGE_PIN J11 [get_ports {oLED_N[12]}]
set_property PACKAGE_PIN J12 [get_ports {oLED_N[15]}]
set_property PACKAGE_PIN J13 [get_ports {oLED_N[14]}]
set_property PACKAGE_PIN K10 [get_ports iBUS_EN]
set_property PACKAGE_PIN K11 [get_ports iBUS_CLK]
set_property PACKAGE_PIN K13 [get_ports ioSYNC_NEIGHBOR]
set_property PACKAGE_PIN L11 [get_ports iBUS_RST]
set_property PACKAGE_PIN L12 [get_ports iBUS_MASTER]
set_property PACKAGE_PIN L13 [get_ports iFPGA_RSTN]
set_property PACKAGE_PIN L14 [get_ports {oFC_RATE_SEL[3]}]
set_property PACKAGE_PIN L33 [get_ports {pci_exp_txp[0]}]
set_property PACKAGE_PIN L34 [get_ports {pci_exp_txn[0]}]
set_property PACKAGE_PIN M10 [get_ports {oFC_RATE_SEL[0]}]
set_property PACKAGE_PIN M11 [get_ports {oFC_RATE_SEL[1]}]
set_property PACKAGE_PIN M12 [get_ports iCLK_FR]
set_property PACKAGE_PIN M14 [get_ports {oFC_RATE_SEL[2]}]
set_property PACKAGE_PIN M31 [get_ports {pci_exp_txp[1]}]
set_property PACKAGE_PIN M32 [get_ports {pci_exp_txn[1]}]
set_property PACKAGE_PIN N10 [get_ports ioSYNC_RIBBON]
set_property PACKAGE_PIN N12 [get_ports {oFC_RATE_SEL[5]}]
set_property PACKAGE_PIN N13 [get_ports {oFC_RATE_SEL[4]}]
set_property PACKAGE_PIN N14 [get_ports {oFC_RATE_SEL[7]}]
set_property PACKAGE_PIN N15 [get_ports {oFC_RATE_SEL[6]}]
set_property PACKAGE_PIN N33 [get_ports {pci_exp_txp[2]}]
set_property PACKAGE_PIN N34 [get_ports {pci_exp_txn[2]}]
set_property PACKAGE_PIN N38 [get_ports {pci_exp_rxp[0]}]
set_property PACKAGE_PIN N39 [get_ports {pci_exp_rxn[0]}]
set_property PACKAGE_PIN P1 [get_ports {iFC_RD_N[25]}]
set_property PACKAGE_PIN P2 [get_ports {iFC_RD_P[25]}]
set_property PACKAGE_PIN P5 [get_ports {oFC_TD_N[25]}]
set_property PACKAGE_PIN P6 [get_ports {oFC_TD_P[25]}]
set_property PACKAGE_PIN P10 [get_ports {oFC_RATE_SEL[9]}]
set_property PACKAGE_PIN P11 [get_ports {oFC_RATE_SEL[8]}]
set_property PACKAGE_PIN P12 [get_ports {oFC_RATE_SEL[11]}]
set_property PACKAGE_PIN P13 [get_ports {oFC_RATE_SEL[10]}]
set_property PACKAGE_PIN P31 [get_ports {pci_exp_txp[3]}]
set_property PACKAGE_PIN P32 [get_ports {pci_exp_txn[3]}]
set_property PACKAGE_PIN P36 [get_ports {pci_exp_rxp[1]}]
set_property PACKAGE_PIN P37 [get_ports {pci_exp_rxn[1]}]
set_property PACKAGE_PIN R3 [get_ports {iFC_RD_N[24]}]
set_property PACKAGE_PIN R4 [get_ports {iFC_RD_P[24]}]
set_property PACKAGE_PIN R7 [get_ports {oFC_TD_N[24]}]
set_property PACKAGE_PIN R8 [get_ports {oFC_TD_P[24]}]
set_property PACKAGE_PIN R33 [get_ports {pci_exp_txp[4]}]
set_property PACKAGE_PIN R34 [get_ports {pci_exp_txn[4]}]
set_property PACKAGE_PIN R38 [get_ports {pci_exp_rxp[2]}]
set_property PACKAGE_PIN R39 [get_ports {pci_exp_rxn[2]}]
set_property PACKAGE_PIN T1 [get_ports {iFC_RD_N[23]}]
set_property PACKAGE_PIN T2 [get_ports {iFC_RD_P[23]}]
set_property PACKAGE_PIN T5 [get_ports {oFC_TD_N[23]}]
set_property PACKAGE_PIN T6 [get_ports {oFC_TD_P[23]}]
set_property PACKAGE_PIN T27 [get_ports sys_clk_p]
set_property PACKAGE_PIN T28 [get_ports sys_clk_n]
set_property PACKAGE_PIN T31 [get_ports {pci_exp_txp[5]}]
set_property PACKAGE_PIN T32 [get_ports {pci_exp_txn[5]}]
set_property PACKAGE_PIN T36 [get_ports {pci_exp_rxp[3]}]
set_property PACKAGE_PIN T37 [get_ports {pci_exp_rxn[3]}]
set_property PACKAGE_PIN U3 [get_ports {iFC_RD_N[22]}]
set_property PACKAGE_PIN U4 [get_ports {iFC_RD_P[22]}]
set_property PACKAGE_PIN U7 [get_ports {oFC_TD_N[22]}]
set_property PACKAGE_PIN U8 [get_ports {oFC_TD_P[22]}]
set_property PACKAGE_PIN U33 [get_ports {pci_exp_txp[6]}]
set_property PACKAGE_PIN U34 [get_ports {pci_exp_txn[6]}]
set_property PACKAGE_PIN U38 [get_ports {pci_exp_rxp[4]}]
set_property PACKAGE_PIN U39 [get_ports {pci_exp_rxn[4]}]
set_property PACKAGE_PIN V1 [get_ports {iFC_RD_N[21]}]
set_property PACKAGE_PIN V2 [get_ports {iFC_RD_P[21]}]
set_property PACKAGE_PIN V5 [get_ports {oFC_TD_N[21]}]
set_property PACKAGE_PIN V6 [get_ports {oFC_TD_P[21]}]
set_property PACKAGE_PIN V31 [get_ports {pci_exp_txp[7]}]
set_property PACKAGE_PIN V32 [get_ports {pci_exp_txn[7]}]
set_property PACKAGE_PIN V36 [get_ports {pci_exp_rxp[5]}]
set_property PACKAGE_PIN V37 [get_ports {pci_exp_rxn[5]}]
set_property PACKAGE_PIN W3 [get_ports {iFC_RD_N[20]}]
set_property PACKAGE_PIN W4 [get_ports {iFC_RD_P[20]}]
set_property PACKAGE_PIN W7 [get_ports {oFC_TD_N[20]}]
set_property PACKAGE_PIN W8 [get_ports {oFC_TD_P[20]}]
set_property PACKAGE_PIN W11 [get_ports {iCLK_FC_425_N[0]}]
set_property PACKAGE_PIN W12 [get_ports {iCLK_FC_425_P[0]}]
set_property PACKAGE_PIN W38 [get_ports {pci_exp_rxp[6]}]
set_property PACKAGE_PIN W39 [get_ports {pci_exp_rxn[6]}]
set_property PACKAGE_PIN Y1 [get_ports {iFC_RD_N[19]}]
set_property PACKAGE_PIN Y2 [get_ports {iFC_RD_P[19]}]
set_property PACKAGE_PIN Y5 [get_ports {oFC_TD_N[19]}]
set_property PACKAGE_PIN Y6 [get_ports {oFC_TD_P[19]}]
set_property PACKAGE_PIN Y36 [get_ports {pci_exp_rxp[7]}]
set_property PACKAGE_PIN Y37 [get_ports {pci_exp_rxn[7]}]
#revert back to original instance
current_instance -quiet
